name: Check for updates

on:
  schedule:
    - cron: '*/2 * * * *' # Runs every 15 minutes

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Check for updates
        run: |
          git fetch
          CHANGES=$(git log HEAD..origin/master --oneline)
          if [ -n "$CHANGES" ]; then
            echo "Changes detected. Trigger the webhook or other actions here."
          else
            echo "No changes detected."
          fi
